/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { RunScriptResult, DeployContractExecutionResult } from "@alephium/cli";
import { NetworkId } from "@alephium/web3";
import {
  FriendTech,
  FriendTechInstance,
  SubjectSharesBalance,
  SubjectSharesBalanceInstance,
  SubjectShares,
  SubjectSharesInstance,
} from ".";
import { default as devnetDeployments } from "../.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    FriendTech: DeployContractExecutionResult<FriendTechInstance>;
    SubjectSharesBalance: DeployContractExecutionResult<SubjectSharesBalanceInstance>;
    SubjectShares: DeployContractExecutionResult<SubjectSharesInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    FriendTech: {
      ...json.contracts["FriendTech"],
      contractInstance: FriendTech.at(
        json.contracts["FriendTech"].contractInstance.address
      ),
    },
    SubjectSharesBalance: {
      ...json.contracts["SubjectSharesBalance"],
      contractInstance: SubjectSharesBalance.at(
        json.contracts["SubjectSharesBalance"].contractInstance.address
      ),
    },
    SubjectShares: {
      ...json.contracts["SubjectShares"],
      contractInstance: SubjectShares.at(
        json.contracts["SubjectShares"].contractInstance.address
      ),
    },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments = networkId === "devnet" ? devnetDeployments : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
