/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as UpdateOwnerScriptJson } from "../scripts/UpdateOwner.ral.json";

export const UpdateOwner = new ExecutableScript<{
  newOwner: Address;
  friendTech: HexString;
}>(Script.fromJson(UpdateOwnerScriptJson));
